"use client"

import { BadgeCheck, Download } from "lucide-react"
import { api, pdfUrl } from "@/lib/api"
import { useApi } from "@/lib/hooks"
import { useI18n } from "@/lib/i18n"
import { Container } from "@/components/common/page-header"
import { ErrorState } from "@/components/common/states"
import { ResultsView } from "@/components/results/results-view"
import { ResultsSkeleton } from "@/app/results/[id]/results-page"
import { buttonVariants } from "@/components/ui/button"

/** Public read-only spec - what the QR code on the PDF opens. */
export function VerifyPage({ shareId }: { shareId: string }) {
  const { t } = useI18n()
  const { data, error, loading, retry } = useApi(() => api.shared(shareId), [shareId])
  return (
    <Container>
      <div className="mb-6 flex flex-col gap-3 rounded-2xl border border-success/40 bg-success/10 p-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-3">
          <BadgeCheck className="size-8 text-success" />
          <div>
            <p className="font-semibold">{t("results.verified")}</p>
            <p className="text-sm text-muted-foreground">
              This spec was generated by the PackSmart engine and has not been changed. Read-only view.
            </p>
          </div>
        </div>
        {data?.shareId && (
          <a href={pdfUrl(data.shareId)} className={buttonVariants({ variant: "outline" })}>
            <Download /> PDF
          </a>
        )}
      </div>
      {loading && <ResultsSkeleton />}
      {error && <ErrorState message={error.includes("not found") ? "This spec does not exist or the link is wrong." : error} onRetry={retry} />}
      {data && <ResultsView result={data} readOnly />}
    </Container>
  )
}
